version: "3.8"
services:
  kryptr_db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: kryptr_db
    ports:
      - 5432:5432

  app:
    build: .
    restart: always
    container_name: app
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - kryptr_db
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1

volumes:
  db_data: