version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: kryptr-gate-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 127.0.0.1:${DB_LOCAL_PORT}:5432

  app:
    build: .
    restart: always
    container_name: kryptr-gate-app
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - ${HOME}/.ssh:/root/.ssh
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1

volumes:
  db_data: