"""empty message

Revision ID: bdc08cc10198
Revises: ebbae42d92c8
Create Date: 2021-04-28 14:18:28.298949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc08cc10198'
down_revision = 'ebbae42d92c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('ecc_password', sa.String(length=32), default=''))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'type')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('accounts', 'ecc_password')
    # ### end Alembic commands ###
