from .auth import auth_blueprint  # noqa f401
from .main import main_blueprint  # noqa f401
from .account import account_blueprint  # noqa f401
from .user import user_blueprint  # noqa f401
from .reseller import reseller_blueprint  # noqa f401
from .distributor import distributor_blueprint  # noqa f401
from .sub_reseller import sub_reseller_blueprint # noqa f401
from .product import product_blueprint # noqa f401
from .support import support_blueprint # noqa f401
